matrix:
  include:
    language: c
    install:
      sudo apt-get install -y build-essential check
    services:
      - docker
    script:
      make test
      make
      cp spell_check your/webroot/
      echo "something random" docker secret create secret_key -
      echo "something random" docker secret create jwt_secret_key -
    language: python
    python:
      - "3.7"
    install:
      - sudo apt-get install python3-pip
      - sudo pip install flask
      - sudo pip install tox
      - sudo pip install tox-travis
    before_script:
      cd your/webroot/
      sudo pip install -r requirements.txt
    script:
      tox
