version: '3.7'
services:
    web:
        image: application-sec:1.0
        deploy:
          replicas: 4
          resources:
            limits:
              cpus: '0.5'
              memory: 350M
            reservations:
              cpus: '0.1'
              memory: 100M
        ports:
            - "8080:8080"
        volumes:
            - .:/app
